#!/usr/bin/env bun
// Walks apps/backend/src/frontend-dist/ and emits an importable TypeScript
// module that statically imports every asset via `with { type: "file" }`,
// so `bun build --compile` embeds them all into the binary.
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..", "apps", "backend", "src");
const DIST = join(ROOT, "frontend-dist");
const OUT = join(ROOT, "embedded-assets.ts");

function walk(dir: string, files: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, files);
    else files.push(p);
  }
  return files;
}

const files = walk(DIST).sort();
const imports: string[] = [];
const entries: string[] = [];
files.forEach((abs, i) => {
  const relToSrc = `./frontend-dist/${relative(DIST, abs)}`;
  const urlPath = `/${relative(DIST, abs)}`;
  imports.push(`import _${i} from "${relToSrc}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: _${i},`);
});

const body = `// GENERATED by scripts/generate-embedded-assets.ts — do not edit.
${imports.join("\n")}
export const EMBEDDED_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(OUT, body);
console.log(`embedded-assets.ts: ${files.length} files`);
