// Единственный источник правды для цветов/шрифтов/z-index.
// Никаких inline констант в JSX по правилам §3.8.
export const tokens = {
  font: {
    sm: 12,
    base: 13,
    mono: "ui-monospace, SFMono-Regular, monospace",
    sans: "system-ui, -apple-system, sans-serif",
  },
  color: {
    text: "#1a1a1a",
    textMuted: "#666",
    border: "rgba(0,0,0,0.12)",
    hoverOverlay: "rgba(0,0,0,0.06)",
    bgPage: "#f6f7f9",
    bg: "#fff",
    bgOverlay: "rgba(255,255,255,0.95)",
    backdrop: "rgba(0,0,0,0.4)",
    accent: "#0a7",
    badgeDev: "#fc6",
    badgeDebug: "#f66",
    badgeBg: "#e5e7eb",
    badgeBorder: "#d1d5db",
    badgeText: "#374151",
    warnBg: "#fef3c7",
    warnBorder: "#f59e0b",
    warnText: "#78350f",
    dangerBg: "#fef2f2",
    dangerBorder: "#fecaca",
    dangerText: "#b91c1c",
    successBg: "#16a34a",
    errorBg: "#c1273a",
    errorText: "#ffffff",
  },
  radius: { sm: 3, md: 6, lg: 8 },
  z: { overlay: 90, banner: 100, modal: 1000, toast: 9999 },
} as const;
